version: '3.4'

services:
  downloaddeleter:
    image: downloaddeleter
    volumes:
      - c:\test_downloads:/downloads
      - c:\test_destination:/destination
    build:
      context: .
      dockerfile: ./Dockerfile
